// SPDX-License-Identifier: Elastic-2.0
namespace GauntletCI.Core.Model;

/// <summary>An individual risk finding produced by a rule during diff analysis.</summary>
/// <remarks>
/// Consolidates core rule output with optional enrichment data.
/// 
/// DESIGN NOTE: Finding combines multiple concerns (rule output + enrichments) which could
/// be separated into CoreFinding + EnrichedFinding wrapper. This separation is deferred pending
/// refactoring impact assessment (116 edges across 60+ files). For now, enrichment fields are
/// clearly documented as optional and separate from required core output fields.
/// </remarks>
public class Finding
{
    /// <summary>The unique identifier of the rule that produced this finding.</summary>
    public required string RuleId { get; set; }

    /// <summary>The human-readable name of the rule that produced this finding.</summary>
    public required string RuleName { get; set; }

    /// <summary>A short description of the detected risk.</summary>
    public required string Summary { get; set; }

    /// <summary>The file, line, and code snippet that triggered the finding.</summary>
    public required string Evidence { get; set; }       // file + line + snippet

    /// <summary>Explains why this pattern is risky and what can go wrong.</summary>
    public required string WhyItMatters { get; set; }

    /// <summary>Actionable guidance on how to address the finding.</summary>
    public required string SuggestedAction { get; set; }

    /// <summary>The confidence level assigned by the detecting rule.</summary>
    public Confidence Confidence { get; set; }

    /// <summary>
    /// The severity of this finding, determining display and exit-code behavior.
    /// Set by <see cref="Rules.RuleOrchestrator"/> from the effective
    /// severity resolved by <see cref="Configuration.ConfigurationService"/>.
    /// </summary>
    public RuleSeverity Severity { get; set; } = RuleSeverity.Info;

    /// <summary>
    /// When set, the orchestrator uses this instead of the rule-level configured severity.
    /// Allows one rule to emit findings at different impact tiers (e.g. GCI0003 compatible vs incompatible signatures).
    /// </summary>
    public RuleSeverity? SeverityOverride { get; set; }

    /// <summary>The path of the file that contains the finding, if applicable.</summary>
    public string? FilePath { get; set; }

    /// <summary>The line number within <see cref="FilePath"/> where the finding was detected.</summary>
    public int? Line { get; set; }

    // === OPTIONAL ENRICHMENT FIELDS ===
    // These fields are populated by enrichment pipeline stages and are not part of core rule output.

    /// <summary>Optional natural-language explanation generated by an LLM enrichment step.</summary>
    public string? LlmExplanation { get; set; }

    /// <summary>Optional expert knowledge fact matched against this finding.</summary>
    public ExpertFact? ExpertContext { get; set; }

    /// <summary>Optional verbatim code snippet extracted from the diff by an LLM evaluation step.</summary>
    public string? CodeSnippet { get; set; }

    /// <summary>Optional coverage annotation added by the Codecov correlation step.</summary>
    public string? CoverageNote { get; set; }

    /// <summary>Optional ticket context fetched from Jira, Linear, or GitHub Issues.</summary>
    public TicketInfo? TicketContext { get; set; }
}
