name: Publish a NuGet package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v6.0.3

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore GauntletCI.slnx

    - name: Build
      run: dotnet build GauntletCI.slnx --no-restore --configuration Release

    - name: Test
      run: dotnet test GauntletCI.slnx --no-build --configuration Release --verbosity minimal

    - name: Pack
      run: dotnet pack src/GauntletCI.Cli/GauntletCI.Cli.csproj --no-build --configuration Release --output packaging/

    - name: Publish to NuGet.org
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push packaging/*.nupkg -k "$NUGET_API_KEY" -s https://api.nuget.org/v3/index.json --skip-duplicate
